#!/bin/bash

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:Ar_KIM_lammps.sh-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-Steven E. Bopp, Materials Science & Engineering-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-June 23, 2021-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-University of California, San Diego-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

Job_Name="Ar_KIM_lammps"             # Give the name you want to apply to all files here
Job_Time="00:05:00"               # Give the run time in hh:mm:ss

KIM_Potential_Name="LJ_Shifted_Bernardes_1958MedCutoff_Ar__MO_126566794224_004"

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:- File History :-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# v_2: This version reduces the number of atoms from 8000 to a cell of 0 5 0 5 0 5, added lattice parameter calculation, added csym calculation, added minimization settings
# run error, cannot give two fix commands that do not have identical style, unresolved as of June 21, 2021
# fixed typo in line: "fix 2 all deform 1 x trate ${srate1} units box remap x" where trate was incorrectly written as erate

# v_3: This version is intended to implement use of a data file as the method of setting up the calculation space and atoms
# for some reason it looks like Atomsk created data files are not working, maybe it has to do with too many spaces in between items?
# ^ resolved: Atomsk will print the datafile with charges for some reason, delete the column with all charges and the file should run correctly
# Runs without errors when using datafile from lammps built-in NaCl example as well as one generated by Atomsk and modified to remove the charge column

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:- Some Helpful Commands for NERSC -:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# ssh -l sbopp -Y cori.nersc.gov                                        # Login command for NERSC
# scp sbopp@cori.nersc.gov:~/Al_results.tar.gz /Users/mainuser/Desktop  # copy from NERSC to me
# scp Al_compression.sh sbopp@cori.nersc.gov:~                          # copy from me to NERSC
# while [ 1 ] ; do clear; ls -lrt; sleep 5; done                        # this will clear screen and list directory every 5 seconds
# while [ 1 ] ; do ls; sleep 5; done                                    # this list directory every 5 seconds
# while [ 1 ] ; do ls; sleep 60; done                                   # this list directory every 60 seconds
# sqs                                                                   # NERSC custom wrapper for the Slurm native squeue, list jobs
# scancel -b -s USR1 43460812                                           # NERSC command cancel job with ID 43460812
# /usr/common/software/lammps                                           # NERSC filesystem location for LAMMPS
# /usr/common/software/berkeleygw                                       # NERSC filesystem location for LAMMPS

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-: Some Helpful Commands for OpenKIM :-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# /usr/common/software/lammps/2021.04.23/bin                            # NERSC filesystem location containing KIM executables
# ./kim-api-collections-management install user MEAM_2NN_Fe_to_Ga__MO_145522277939_001

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-: Some Helpful Commands for Atomsk -:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# sudo apt install /home/ubuntu-budgie/Desktop/atomsk_b0.11_amd64.deb   # Install Atomsk. Make sure you are connected to the internet to install Atomsk
# atomsk TiN_493atoms.pdb lammps                                        # Create a lammps datafile from TiN_498atoms.pdb
# atomsk --create fcc 4.046 Al lammps                                   # Create a lammps datafile for Al with one element
# atomsk --create fcc 4.95 Ti N lammps                                  # Create a lammps datafile for FCC TiN with Ti and N elements

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:- Calculate Compression of Al Atoms with LAMMPS -:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:- Original files located at -:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-: https://icme.hpc.msstate.edu/mediawiki/index.php/Uniaxial_Compression.html -:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

#START_TIME=$SECONDS # Begin elapsed time measurement (thanks Tom Anderson from StackOverflow)

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-: Begin LAMMPS File Creation -:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

echo " Running script ${Job_Name}.sh..."

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-: Create SBATCH Script for NERSC -:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:- NERSC SBATCH Run Options :-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:- The following is for MPI jobs, not serial -:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:- Do not use srun for serial executables :-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
     #SBATCH --job-name=myjob     # Replacable with -J myjob
     #SBATCH --constraint=haswell # Replacable with -C haswell (or other cpu)
     #SBATCH --qos=debug          # Replacable with -q debug   (whcih queue the script will run on)
     #SBATCH --nodes=1            # Replacable with -N xxxxxx  (no. of nodes on whcih calc. will run)
     #SBATCH --tasks-per-node=2
     #SBATCH --cpus-per-task=16
     #SBATCH --time=00:05:00      # Replacable with -t xx:xx:xx
     #SBATCH --account=m3047
     #SBATCH --output=myjob.o%j
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-: Create SBATCH Script for NERSC -:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# Here cat will automatically insert the Job_Name variable into the SBATCH --job-name option as well as the file name it creates
# Make sure that the variable in the file name is written as ${Job_Name}.extension so that BASH knows where the variable name ends and the extension begins
# Make sure that there is no space before the #!/bin/bash shebang line
# concatenate command used to be: cat > Al_compression_lammps.sb << EOF
# **VERY IMPORTANT** EOF is NOT quoted so that $Job_Name will be printed as the stored variable and not as "${Job_Name}" in the file

cat > ${Job_Name}.sb << EOF
#!/bin/bash
#SBATCH --job-name=$Job_Name
#SBATCH --constraint=haswell
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --tasks-per-node=2
#SBATCH --cpus-per-task=16
#SBATCH --time=$Job_Time
#SBATCH --account=m3047
#SBATCH --output=$Job_Name.o%j

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=16

## Environment
module load lammps

srun lmp_cori -in ${Job_Name}.in

EOF

echo " Creating input file ${Job_Name}.sb..."
echo "  done"

#ELAPSED_TIME1=$(($SECONDS - $START_TIME))
#echo "It has been ${ELAPSED_TIME1} seconds"

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:- Create Input File for LAMMPS :-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

# Here, cat will automatically insert the Job_Name variable into the LAMMPS input file name it creates
# Make sure that the variable in the file name is written as ${Job_Name}.extension so that BASH knows where the variable name ends and the extension begins
# **VERY IMPORTANT** EOF is quoted so that ${latparam} will be printed in the file (thanks to dogbane from StackOverflow)

cat > ${Job_Name}.in << "EOF"
# 3d Lennard-Jones melt

variable     x index 1
variable     y index 1
variable     z index 1

variable     xx equal 20*$x
variable     yy equal 20*$y
variable     zz equal 20*$z

units        real

lattice      fcc 4.4300
region       box block 0 ${xx} 0 ${yy} 0 ${zz}
create_box   1 box
create_atoms 1 box

pair_style   lj/cut 8.1500
pair_coeff   1 1 0.0104 3.4000

#pair_style  kim LennardJones_Ar
#pair_coeff  * * Ar

mass         1 39.95
velocity     all create 200.0 232345 loop geom

neighbor     0.3 bin
neigh_modify delay 0 every 1 check yes

fix          1 all nve
#fix         1 all npt temp 1.0 1.0 1.0 iso 1.0 1.0 3.0

run          100


EOF

echo " Creating input file ${Job_Name}.in..."
echo "  done"

#ELAPSED_TIME2=$(($SECONDS - $START_TIME))
#echo "It has been $ELAPSED_TIME2 seconds"

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-: Run LAMMPS Calcuation with SBATCH :-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

echo " Submitting ${Job_Name}.sb via sbatch..."

sbatch ${Job_Name}.sb

echo "  done"

#ELAPSED_TIME4=$(($SECONDS - $START_TIME))
#echo "It has been $ELAPSED_TIME4 seconds"

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:End Elapsed Time Measurement-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-

#ELAPSED_TIME=$(($SECONDS - $START_TIME))
#echo "It has been $ELAPSED_TIME seconds"

sqs # NERSC command to cat out the job that has been submitted

echo "Success, End of Script"

#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:TiN_lammps_v2.sh-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-Steven E. Bopp, Materials Science & Engineering-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-June 21, 2021-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-University of California, San Diego-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-End of File-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
#-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-:-
